---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Gemspec/RequiredRubyVersion:
  Exclude:
  - eac_redmine_base0.gemspec
Style/RedundantConstantBase:
  Exclude:
  - eac_redmine_base0.gemspec
  - init.rb
  - lib/tasks/eac_redmine_base0.rake
